### ISSUE TITLE
error when installing via pip (using windows)

### ISSUE THREAD

**Issue by Kraut-Inferences** [ml-jku/hopfield-layers#29]
when installing i get the following error: 
Collecting git+https://github.com/ml-jku/hopfield-layers
  Cloning https://github.com/ml-jku/hopfield-layers to c:\users\magma\appdata\local\temp\pip-req-build-hqlogu8q
  Running command git clone --filter=blob:none -q https://github.com/ml-jku/hopfield-layers 'C:\Users\Magma\AppData\Local\Temp\pip-req-build-hqlogu8q'
  Resolved https://github.com/ml-jku/hopfield-layers to commit f56f929c95b77a070ae675ea4f56b6d54d36e730
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\users\magma\appdata\local\programs\python\python36\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Magma\\AppData\\Local\\Temp\\pip-req-build-hqlogu8q\\setup.py'"'"'; __file__='"'"'C:\\Users\\Magma\\AppData\\Local\\Temp\\pip-req-build-hqlogu8q\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Magma\AppData\Local\Temp\pip-pip-egg-info-_zr1l4u_'
       cwd: C:\Users\Magma\AppData\Local\Temp\pip-req-build-hqlogu8q\
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Magma\AppData\Local\Temp\pip-req-build-hqlogu8q\setup.py", line 4, in <module>
      long_description = readme_handle.read()
    File "C:\users\magma\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3096: character maps to <undefined>
  ----------------------------------------
WARNING: Discarding git+https://github.com/ml-jku/hopfield-layers. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Nix-da** [comment]
Hi, I had the same problem and created a fork of this repo where I fiexed it. If you still have the problem you may check it out (until the original Lib does)

**Comment by Tigxy** [comment]
Hi!
I had the same issue. I bypassed it by setting the environment variable `PYTHONUTF8` to `1`, i.e., execute 
`set PYTHONUTF8=1`. @Nix-da 's solution is definitely better, but it did the job.

Check out https://stackoverflow.com/a/64549704 for some more information :)
